config/routes.rb
RailsStore::Application.routes.draw do

  resources :reviews, :only => [:new, :create]

  resources :products

  root :to => 'products#index'

  get '/reviews/new/:id' => 'reviews#new'

  match '/products/:id/addcart' => 'products#addcart'
  match '/products/:id/remcart' => 'products#remcart'

   

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :price, :body, :product_id, :rating, :image, :in_cart

  has_many :reviews

  validates_uniqueness_of :name
  validates_presence_of :price

  

end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :body, :product_id, :rating

  belongs_to :product

  validates_length_of :body, :within => 50..1000
  validates_inclusion_of :rating, :in => 0..5
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery



  def home

  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json

  # attr_accessor :products
  # before_filter :products_defined
  before_filter :products_in_cart
  # # private :product_finder

  def products_in_cart
    @products_in_cart = Product.where(:in_cart => true).all
    @products_not_in_cart = Product.where(:in_cart => false).all
    # @product = Product.find(params[:id])
  end


  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  def addcart
    @product = Product.find(params[:id])
    @product.in_cart = true
    @product.save
    @product.update_attributes({:in_cart => true})
  end

  def remcart
    @product = Product.find(params[:id])
    @product.in_cart = false
    @product.save
    @product.update_attributes({:in_cart => false})
  end

  # GET /products/1
  # GET /products/1.json
  def show
    # @review = Review.connection.select_all("SELECT "reviews".* FROM "reviews" WHERE "reviews"."product_id" = params[:id];")
    # # @review = Review.all
    @product = Product.find(params[:id])
    @review = Review.where(:product_id => params[:id]).all

    # Review.find(params[:id])
    
    # @pname = @products.find(params[:id]).name
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
        @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
        @product = Product.find(params[:id])
    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # GET /reviews
  # GET /reviews.json
  # attr_accessor :products

  def index
    @reviews = Review.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reviews }
    end
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @review = Review.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/new
  # GET /reviews/new.json
  def new
    @review = Review.new

    # @products = Product.all
    @pname = Product.find(params[:id]).name

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/1/edit
  def edit
    @review = Review.find(params[:id])
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(params[:review])

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render json: @review, status: :created, location: @review }
      else
        format.html { render action: "new" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reviews/1
  # PUT /reviews/1.json
  def update
    @review = Review.find(params[:id])

    respond_to do |format|
      if @review.update_attributes(params[:review])
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    respond_to do |format|
      format.html { redirect_to reviews_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/application/home.erb
<a href='/products'>Products</a>
<p>
<a href='/reviews'>Reviews</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsStore</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>





<%= yield %>

</body>
</html>

app/views/products/_cart.html.erb
Cart:
<% @x = 0.0 %>

<% @products_in_cart.each_index do |i|%>
<%= @products_in_cart[i]["name"] %>
<%= number_to_currency@products_in_cart[i]["price"] %>
<% end %>
<p>



Total: 

<% @products_in_cart.each_index do |i| %>
<% @x += @products_in_cart[i]["price"]%>
<% end %>

<%= number_to_currency@x %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
    <div class="field">
    <%= f.label :in_cart %><br />
    <%= f.check_box :in_cart %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/addcart.html.erb
    <%= form_for @product do |f| %>
      <% if !@product.in_cart%>
        <%= f.hidden_field :in_cart, :value => true %>
        <%= f.submit "Add to Cart" %>
      <% end %>
    <% end %>


  <script type="text/javascript">
    window.location.href="/" 
  </script>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th>Add to Cart</th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= number_to_currency(product.price) %></td>
    <td>

<% if !product.in_cart %>
<button>
<a href="/products/<%= product.id %>/addcart">Add to Cart</a>
</button>
<% else %>
<button>
<a href="/products/<%= product.id %>/remcart">Remove from Cart</a>
</button>
<% end %>
<!--       <form action='/products/:id/addcart' method='post'>   
        <input type='hidden' value='product.in_cart'/>
        <button>Add to Cart</button>
      </form> -->
    </td>

    <td><a href="/reviews/new/<%= product.id %>">Review!</a></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<%= render 'cart' %>


<br />

<%= link_to 'New Product', new_product_path %>

<%= link_to 'Home', home_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/remcart.erb
    
    <%= form_for @product do |f| %>
      <% if @product.in_cart%>
        <%= f.hidden_field :in_cart, :value => false %>
        <%= f.submit "Remove from Cart" %>
      <% end %>
    <% end %>

  <script type="text/javascript">
    window.location.href="/" 
  </script>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Price:</b>
  <%= number_to_currency@product.price %>
</p>



<% @review.each_index do |i|   %>

  <b>Body:</b>
  <%= @review[i]["body"] %>
</p>


<p>
  <b>Rating:</b>
  <%= @review[i]["rating"] %>
</p>


<% end %>

<%= render 'cart' %>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.hidden_field :product_id, :value => params[:id] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table>
  <tr>
    <th>Body</th>
    <th>Rating</th>
    <th>Product</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reviews.each do |review| %>
  <tr>
    <td><%= review.body %></td>
    <td><%= review.rating %></td>
    <td><%= review.product_id %></td>
    <td><%= link_to 'Show', review %></td>
    <td><%= link_to 'Edit', edit_review_path(review) %></td>
    <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<a href="/home">Home</a>

app/views/reviews/new.html.erb
<h1>New review</h1>
<p>Write a review for <%= @pname %>!
<p>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>

  <b>Body:</b>
  <%= @review.body %>
</p>

<p>
  <b>Rating:</b>
  <%= @review.rating %>
</p>

<p>
  <b>Product:</b>
  <%= @review.product_id %>
</p>


<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>